apiVersion: v1
kind: Secret
metadata:
  name: {{ include "falkordb-browser.fullname" . }}
  labels:
    {{- include "falkordb-browser.labels" . | nindent 4 }}
type: Opaque
stringData:
  NEXTAUTH_SECRET: {{ .Values.env.nextauthSecret | quote }}
