apiVersion: v1
kind: Service
metadata:
  name: {{ include "falkordb-browser.fullname" . }}
  labels:
    {{- include "falkordb-browser.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.restPort }}
      targetPort: rest
      protocol: TCP
      name: rest
    - port: {{ .Values.service.mcpPort }}
      targetPort: mcp
      protocol: TCP
      name: mcp
  selector:
    {{- include "falkordb-browser.selectorLabels" . | nindent 4 }}
