apiVersion: v2
name: falkordb-browser
description: A Helm chart for deploying FalkorDB Browser to Kubernetes
type: application
version: 1.6.7
appVersion: "1.6.7"
keywords:
  - falkordb
  - browser
  - graph
  - database
home: https://github.com/FalkorDB/falkordb-browser
sources:
  - https://github.com/FalkorDB/falkordb-browser
maintainers:
  - name: FalkorDB
    url: https://www.falkordb.com
